name: azure-calico-user-defined-routes
namespace: kube-system
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/azure-calico-user-defined-routes
  tag: [[ .Version ]]
  pullPolicy: IfNotPresent

cidr: ""
