version: 2.1
orbs:
  architect: giantswarm/architect@3.3.0

workflows:
  package-and-push-docker-image-and-chart:
    jobs:
      # build and push docker image to quay.
      - architect/push-to-docker:
          context: "architect"
          name: push-calico-policy-only-to-quay
          image: "quay.io/giantswarm/calico-policy-only"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
      # build and push chart
      - architect/push-to-app-catalog:
          context: "architect"
          # executor: "app-build-suite" # uncomment this if you want automatic metadata generation
          name: "package and push calico-policy-only-app chart"
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "calico-policy-only"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
