apiVersion: v1
appVersion: 0.0.1
description: A Helm chart to apply needed iptables rules in order for Calico user defined routes to work on Azure.
engine: gotpl
home: https://github.com/giantswarm/calico-policy-only-app
icon: https://s.giantswarm.io/app-icons/project-calico/1/light.svg
name: calico-policy-only
sources:
- https://github.com/giantswarm/calico-policy-only-app
version: [[ .Version ]]
